#!/bin/bash

font=${EC_TERM_FACE:-xft:Terminus:size=12,[codeset=iso8859-7]xft:Andale Mono:size=12}

frg="grey60"
bkg="#101010"
bkg="black"
bkg="grey5"
bw=${EC_TERM_BORDER:-2}
tr=${EC_TRANS_SPEC}
usr=${EC_USR_OPTS}

exec urxvtcd -cr tomato -sl 0 +ptab +rv +ssr -b $bw -bd "$bkg" \
             -bg "$bkg" -fg "$frg" \
             +sbg $tr -fn "${font}" -name "emacsclient" \
             -xrm "*colorBD: ${frg}" \
             -xrm "*colorUL: ${frg}" \
             -xrm "*color0: ${bkg}" \
             -xrm "*color8: grey20" \
             -xrm "*color1: lightgoldenrod3" \
             -xrm "*color9: sienna3" \
             -xrm "*color2: darkseagreen4" \
             -xrm "*color10: #44836e" \
             -xrm "*color3: grey40" \
             -xrm "*color11: #648f81" \
             -xrm "*color4: lightcyan4" \
             -xrm "*color12: darkseagreen4" \
             -xrm "*color5: paleturquoise4" \
             -xrm "*color13: aquamarine4" \
             -xrm "*color6: grey7" \
             -xrm "*color14: grey40" \
             -xrm "*color7: ${frg}" \
             -xrm "*color15: grey50" \
             ${usr} \
             -e emacsclient -t $*
