#!/bin/bash

font=${EC_TERM_FACE:-xft:Inconsolata-11}
ifont=${EC_TERM_ITALIC_FACE}

frg="grey80"
bkg="black"
bw=${EC_TERM_BORDER:-2}
tr=${EC_TRANS_SPEC}
usr=${EC_USR_OPTS}

exec urxvtcd $tr -cr tomato +ptab -bg "$bkg" -bd "$bkg" -fg "$frg" \
             -sl 0 +rv +ssr -b $bw +sbg -fn "${font}" -fi "${ifont}" \
             -name "emacsclient" ${usr} \
#             -e emacsclient -t $*

# exec xterm -cr tomato -b $bw -fa $font -fi $EC_TERM_ITALIC_FACE \
#            -fg $frg -bg $bkg
#            -e emacsclient -t $*

exec urxvtcd -cr tomato -sl 0 +ptab +rv +ssr -b $bw -bd "$bkg" \
             -bg "$bkg" -fg "$frg" \
             +sbg $tr -fn "${font}" -name "emacsclient" \
             -xrm "*colorBD: ${frg}" \
             -xrm "*colorUL: ${frg}" \
             -xrm "*color0: ${bkg}" \
             -xrm "*color8: grey20" \
             -xrm "*color1: lightgoldenrod4" \
             -xrm "*color9: sienna3" \
             -xrm "*color2: darkseagreen4" \
             -xrm "*color10: #44836e" \
             -xrm "*color3: grey40" \
             -xrm "*color11: #648f81" \
             -xrm "*color4: lightcyan4" \
             -xrm "*color12: darkseagreen4" \
             -xrm "*color5: paleturquoise4" \
             -xrm "*color13: aquamarine4" \
             -xrm "*color6: grey7" \
             -xrm "*color14: grey40" \
             -xrm "*color7: ${frg}" \
             -xrm "*color15: grey50" \
             ${usr} \
             -e emacsclient -t $*
