(jao-define-custom-theme jao-dark-blue
  (:palette (fg unspecified "grey77")
            ;; (bg unspecified "#3f3f3f")
            ;; (bg unspecified "#0e1111")
            (bg unspecified "#192021")
            (box "color-237" "grey25")
            (button ((c 240) nul)
                    ;; ((c "lightskyblue2" "#3f3f4f"))
                    ((c "lightskyblue2" "#333436") nul))
            (hilite ((c nil "#303336")))
            (strike-through ((c 237)) (st))
            (italic ((c 137) it) (it (c "lightyellow3")))
            ;; (link ((c 108) nul) ((c "#F0DFAF") nit nul))
            ;; (visited-link ((c 36) nul) ((c "#E0CF9F") nul))
            (link ((c "antiquewhite3") nit nul))
            ;; (link ((c "lemonchiffon") nit nul))
            (visited-link ((c "burlywood3") nit nul))
            (tab-sel ((c 252 232) nbf))
            (tab-unsel ((c 245 232)))
            (comment ((c 102) it) ((c "lightsteelblue4") it))
            ;; (keyword ((c 151) nbf nul nit) ((c "darkseagreen3")))
            ;; (function ((c 115) nul nbf) ((c "palegreen3")))
            (keyword ((c 151) nbf nul nit) ((c "lightblue3")))
            ;; (function ((c 115) nul nbf) ((c "lightskyblue3")))
            (function ((c 115) nul nbf) ((c "cadetblue3")))
            (type ((c 72) nbf) ((c "honeydew3")))
            (variable-name ((c nil)))
            ;; (constant ((c 72)) ((c "lavenderblush4")))
            (constant ((c 72)) ((c "slategray3") nbf nit nul))
            ;; (string ((c 36)) ((c "thistle4")))
            (string ((c 36)) ((c "cadetblue")))
            (warning ((c 144)) ((c "#F0DFAF")))
            (error ((c 95)) ((c "goldenrod3")))
            ;; (dimm ((c 240)))
            (dimm ((c 59)) ((c "#6f6f6f")))
            (gnus-mail ((c "gray70" nil)))
            (gnus-news ((c "gray70" nil)))
            ;; (outline ((c "aquamarine3")))
            (outline ((c nil)))
            (f00 ((c 29)) ((c "slategray3")))
            (f01 ((c 108)) ((c "cadetblue")))
            (f02 ((c 102)) ((c "lightcyan4"))) ;; ((c "paleturquoise4"))
            (f10 ((c "cornsilk3")))
            (f11 ((c "lemonchiffon3")))
            (f12 ((c "azure3"))))
  (:faces (bold (c nil nil) nul)
          (button (c 66))
          (font-lock-doc-face (c 30))
          (gnus-button (c nil) nul)
          (gnus-header-subject (p f01))
          (gnus-summary-selected (c 250))
          ;; (gnus-summary-selected (c 66 nil) nul nbf)
          (match ul)
          (magit-log-tag-label (c 95 240) nbf)
          (mm-uu-extract (c nil 234))
          (mode-line (c 248 235) nbf nul)
          (mode-line-inactive (c 243 235) nbf nul)
          (org-hide (c 0 nil))
          (rcirc-other-nick (c 108))
          (vertical-border (c 59 nil) :inherit nil)
          (w3m-image (c 144))
          (w3m-tab-background (c 0 0) ul)
          (w3m-tab-line (c 0 0) ul)
          (widget-button (c 196))
          (widget-field (c 143 236)))
  (:x-faces (company-scrollbar-bg (c nil "#383941"))
            (company-scrollbar-fg (c nil "#484951"))
            (diff-hl-change (c "#3f3f3f" "darkseagreen4"))
            (diff-hl-delete (c "#3f3f3f" "goldenrod4"))
            (diff-hl-insert (c "#3f3f3f" "cadetblue4"))
            (font-lock-doc-face (c "lightcyan3") it)
            (fringe (p dimm))
            (gnus-button (c "lightyellow3") nul)
            (gnus-summary-cancelled  (c "dark slate gray" nil) st)
            (gnus-summary-selected (p warning) nul nbf)
            (header-line (p hilite))
            (mode-line (c "grey60" "#2f2f2f"))
            (mode-line-inactive (c "grey50" "#3f3f3f"))
            (org-hide (c 0 nil))
            (show-paren-match (c "darkseagreen1" "#5f5f5f"))
            (spaceline-read-only (c "lightgoldenrod2" "gray10") niv)
            (spaceline-modified (c "burlywood3" "gray10") nbf nit)
            (spaceline-unmodified (c "darkseagreen" "gray10") niv)
            (variable-pitch (c nil nil))
            (vertical-border (c "#3f3f3f") :inherit nil)
            (w3m-image (c "lightcyan2"))
            (w3m-tab-background (c nil nil))
            (w3m-tab-line (c 0 0) ul)
            (widget-button (c nil nil) nul))
  (:x-colors "lemonchiffon"
             "sienna3"
             "darkseagreen3"
             "lightgoldenrod3"
             "cadetblue4"
             "lightcyan4"
             "cadetblue3"
             "black"))

(provide 'jao-dark-blue-theme)
