(jao-define-custom-theme jao-light
  (:palette (fg unspecified "black")
            (bg unspecified "white")
            (box "grey80" "antiquewhite3")
            (button ((c 13 nil) nbf nul) (~ mode-line-inactive))
            (hilite ((c nil "grey90")) ((c nil 15))) ;; 5
            (strike-through ((c 1)) (st))
;;            (italic ((c nil) it :family "DejaVu Sans Mono" :height 90))
;;            (italic ((c "darkslategray4")))
;;            (italic (it))
            (italic (it :family "Inconsolata LGC" :height 90))
            (link ((c 22) nul nbf nit) ((c 29) nul nbf))
            (visited-link ((c 23) nul nbf))
            (tab-sel ((~ mode-line)))
            (tab-unsel ((~ mode-line-inactive)))
            (comment ((c 241) it :family "Inconsolata LGC" :height 90))
;;            (comment ((c 241) it))
;;            (keyword ((c 24 nil) nbf))
            (keyword ((c "lightsteelblue4" nil) bf))
            (type ((c 59) nbf nul nit) ((c 14) nbf))
            (function ((c 30 nil) nbf))
;;                      ((c 30 nil) nit :family "Inconsolata LGC" :height 90))
;;            (function ((c 31 nil) nbf) ((c 0 nil) nbf it ul))
            (variable-name ((c 0)))
            (constant ((c 23)))
            (string ((c 58)) ((c 29)))
            (warning ((c 9)))
            (error ((c 1)))
            (dimm ((c 102)) ((c 12)))
            (gnus-mail ((c 232)) ((c 0)))
            (gnus-news ((c 232)) ((c 0)))
            (outline ((c 0)))
            (f00 ((c 30)) ((c 23))) ;; 14
            (f01 ((c 31)) ((c 24)))
            (f02 ((c 37)) ((c 30))) ;; 8
            ;; (f00 ((c 8))) ;; 14
            ;; (f01 ((c 14)))
            ;; (f02 ((c 10))) ;; 8
            (f10 ((p f00)))
            (f11 ((p f01)))
            (f12 ((p f02))))
  (:faces (bold bf)
          (button (c 31) nul nbf)
          (company-tooltip-common (c 1 6) nbf)
          (company-tooltip-common-selection (~ company-tooltip-selection)
                                            (c nil 6) bf)
          (company-tooltip-selection (~ company-tooltip) bf nul)
          (compilation-info (c nil nil) bf)
          (diary (c 14) bf)
          (gnus-summary-selected (c 240 nil) nul)
          (gnus-summary-cancelled (c nil 230) nul)
          (gnus-summary-normal-unread (c 0 nil))
          (header-line (c nil 15) nul)
          (italic it)
          (mode-line (c 0 "grey90") nbf nul)
          (mode-line-inactive (c 11 "grey90") nbf nul)
          (org-hide (c 15 15))
          (powerline-active1 (c "black" "grey85"))
          (powerline-active2 (c "grey5" "grey80"))
          (powerline-inactive1 (c "grey20" "grey95"))
          (powerline-inactive2 (c "grey20" "grey90"))
          (vertical-border (c 252 nil) :inherit nil)
          (w3m-tab-selected (c 9 nil) bf)
          (w3m-link-numbering (c 12))
          (w3m-bold (c nil nil) bf)
          (w3m-image (c 94))
          (w3m-tab-background (c 12 15)))
  (:x-faces (bold (c 14) bf)
            (button (c 10 nil) nbf)
            (gnus-button (c nil nil) nbf)
            (compilation-info (c 14 nil) nbf)
            (cursor (c 1 1))
            (diary (p error) nbf)
            (diff-hl-change (c "white" "lemonchiffon1"))
            (diff-hl-insert (c "white" "honeydew2"))
            (diff-hl-delete (c "white" "wheat1"))
            (fringe (c "grey70" nil))
            (gnus-summary-selected (c 2) nbf)
            (gnus-summary-cancelled (c 1) st)
            (header-line (c nil "#efebe7"))
            (lui-track-bar (c "red" nil) :height 0.8 ul st :overline t)
            ;; (mode-line (c "grey15" 7) :box (:line-width -1 :color "grey90"))
            ;; (mode-line-inactive (c "grey30" "grey97")
            ;;                     :box (:line-width -1 :color "grey90"))
            ;; (mode-line (c "grey20" "grey90") :box nil)
            ;; (mode-line-inactive (c "grey40" "grey96") :box nil)
            (mode-line (c "grey20" "grey90") :box nil)
            (mode-line-inactive (c "grey40" "white smoke") :box nil)
            (mode-line-buffer-id (c "orange4") nbf it)
            (powerline-active1 (c "black" "grey85"))
            (powerline-active2 (c "grey5" "grey80"))
            (powerline-inactive1 (c "grey20" "grey95"))
            (powerline-inactive2 (c "grey20" "grey90"))
            (org-hide (c "white" "white"))
            (vertical-border (c "grey70" nil))
            (w3m-image (c "midnightblue" "azure2"))
            (w3m-bold (c 10) bf)
            (w3m-tab-selected (c 9 15) bf)
            (w3m-tab-selected-retrieving (~ w3m-tab-selected) (c 1))
            (w3m-tab-background (c 15 15) nul))
  (:x-colors "black" "sienna3" "#597B59" "#D38108" "#3B3152"
             "#E0DACC" "lightyellow3"
             "#EFEBE7" "grey20" "orangered4" "darkslategray" "#59513A"
             "lemonchiffon4" "#386858" "#223142" "#EFEBE7"))

(provide 'jao-light-theme)
