#!/bin/bash

frg="black"
bkg="#EFEBE7"
bkg="white"

bw=${EC_TERM_BORDER:-1}
tr=${EC_TRANS_SPEC}
usr=${EC_USR_OPTS}

font=$EC_TERM_FACE
ifont=$EC_TERM_ITALIC_FACE

exec xterm $usr -b $bw -fg "$frg" -bg "$bkg" -e emacsclient -t $*

exec urxvtcd $tr -cr tomato +ptab -bg "$bkg" -bd "$bkg" -fg "$frg" \
             -sl 0 +rv +ssr -b $bw +sbg -fn "${font}" -fi "${ifont}" \
             -xrm "*colorBD: grey20" \
             -xrm "*colorUL: grey20" \
             -xrm "*color0: ${frg}" \
             -xrm "*color8: grey20" \
             -xrm "*color1: sienna3" \
             -xrm "*color9: orangered4" \
             -xrm "*color2: #597B59" \
             -xrm "*color10: #254242" \
             -xrm "*color3: #D38108" \
             -xrm "*color11: #59513A" \
             -xrm "*color4: #3B3152" \
             -xrm "*color12: lemonchiffon4" \
             -xrm "*color5: #E0DACC" \
             -xrm "*color13: #386858" \
             -xrm "*color6: lightyellow3" \
             -xrm "*color14: #1F3D4F" \
             -xrm "*color7: ${bkg}" \
             -xrm "*color15: #EFEBE7" \
             -name "emacsclient" ${usr} \
             -e emacsclient -t $*
